[pytest]
pythonpath = src

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --alluredir=allure_results
    --clean-alluredir
    -v
markers =
    smoke: Дымовые тесты
    regress: Регрессионные тесты
    api: API тесты
